name: pruebas y construccion 

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Unzip application files
        run: unzip api-codigo.zip -d .

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
         java-version: '11'
        
         distribution: 'temurin'
         server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
         settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build with Maven
        run: ./mvnw verify --file pom.xml

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: application-jar
          path: |
            **/target/*.jar


